name: build
on:
  pull_request:
    branches: [main, develop, release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘· Realiza build do projeto
        run: echo "ğŸ‘· build iniciada por ${{ github.actor }}"
      
      - name: ğŸ”¦ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ§° Setup node
        uses: actions/setup-node@v4

      - name: âš’ï¸ Build EasyCrit frontend
        run: |
          npm i
          npm run build
