name: style & lint
on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ–Œï¸ Analise de estilo no cÃ³digo
        run: echo "ğŸ–Œï¸ Analizando e corrigindo cÃ³digo para encontrar erros de estilo."
      
      - name: ğŸ”¦ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ§° Setup node
        uses: actions/setup-node@v4

      - name: ğŸ¨ Prettier
        run: |
          npm i
          npm run check-style

      - name: âŒ Em caso de falha
        if: failure()
        run: echo "ğŸš« O prettier encotrou erros de estilo" && echo "Use o comando 'npm run style' para corrigir automaticamente"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§¼ AnÃ¡lise estÃ¡tica de cÃ³digo
        run: echo "ğŸ§¼ Procurando por erros e bugs, alÃ©m de erros de estilo no cÃ³digo"

      - name: ğŸ”¦ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ§° Setup node
        uses: actions/setup-node@v4

      - name: ğŸ› eslint
        run: |
          npm i
          npm run lint
      
      - name: âŒ Em caso de falha
        if: failure()
        run: echo "ğŸš« O eslint encontrou possÃ­veis erros, bugs ou erros de estilo no cÃ³digo" && echo "Use o comando 'npm run lint' para visualizar os erros e corrigi-los"
